// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCba0UQC98OYnb2Xg_K6HZVjYTg0Vl6F7E',
    appId: '1:34759246473:web:b94920e54032faa9f6fc58',
    messagingSenderId: '34759246473',
    projectId: 'teikerapp-45ae5',
    authDomain: 'teikerapp-45ae5.firebaseapp.com',
    storageBucket: 'teikerapp-45ae5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRUWaT04OOiYzicxAvv4EcYRN1ege1dec',
    appId: '1:34759246473:android:6f6d3936e98cf024f6fc58',
    messagingSenderId: '34759246473',
    projectId: 'teikerapp-45ae5',
    storageBucket: 'teikerapp-45ae5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRqJuz4sMGc0nwGhJScqE90_UhClttiiI',
    appId: '1:34759246473:ios:a63f36fb6fa42f36f6fc58',
    messagingSenderId: '34759246473',
    projectId: 'teikerapp-45ae5',
    storageBucket: 'teikerapp-45ae5.firebasestorage.app',
    iosBundleId: 'com.example.teikerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRqJuz4sMGc0nwGhJScqE90_UhClttiiI',
    appId: '1:34759246473:ios:a63f36fb6fa42f36f6fc58',
    messagingSenderId: '34759246473',
    projectId: 'teikerapp-45ae5',
    storageBucket: 'teikerapp-45ae5.firebasestorage.app',
    iosBundleId: 'com.example.teikerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCba0UQC98OYnb2Xg_K6HZVjYTg0Vl6F7E',
    appId: '1:34759246473:web:2c0ba58123f452e8f6fc58',
    messagingSenderId: '34759246473',
    projectId: 'teikerapp-45ae5',
    authDomain: 'teikerapp-45ae5.firebaseapp.com',
    storageBucket: 'teikerapp-45ae5.firebasestorage.app',
  );
}
